# Generated by Django 4.0.3 on 2022-05-06 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provide_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('address', models.CharField(max_length=100, verbose_name='Endereço')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('district', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=50, verbose_name='Cidade')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('date_create', models.DateField(verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['-date_create'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30, verbose_name='Marca')),
                ('vehicle', models.CharField(max_length=40, verbose_name='Modelo')),
                ('color', models.CharField(max_length=20, verbose_name='Cor')),
                ('plate', models.CharField(max_length=10, verbose_name='Placa')),
                ('date_create', models.DateField(verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['-date_create'],
            },
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_traffic', models.CharField(max_length=50, verbose_name='Marca')),
                ('departure_date', models.DateField(verbose_name='Data de saída')),
                ('departure_time', models.TimeField(verbose_name='Hora da saída')),
                ('km_of_exit', models.IntegerField(verbose_name='Km de saída')),
                ('destiny', models.CharField(max_length=100, verbose_name='Destino')),
                ('arrival_date', models.DateField(verbose_name='Data de chegada')),
                ('arrival_time', models.TimeField(verbose_name='Hora de chegada')),
                ('arrival_kml', models.IntegerField(verbose_name='Km de chegada')),
                ('service_purpose', models.CharField(max_length=200, verbose_name='Finalidade do serviço')),
                ('difference', models.IntegerField(verbose_name='Diferença')),
                ('drivers_name', models.CharField(max_length=100, verbose_name='Nome do motorista')),
                ('asked_by', models.CharField(max_length=100, verbose_name='Solicitado por')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Controle de tráfego',
                'verbose_name_plural': 'Controles de tráfegos',
                'ordering': ['vehicle'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_ofag_liters', models.FloatField(verbose_name='Quant de litros')),
                ('milee', models.FloatField(verbose_name='Kilometragem')),
                ('supply_value', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor do abastecimento')),
                ('payment', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], max_length=3, verbose_name='Pagamento')),
                ('driver_name', models.CharField(max_length=50, verbose_name='Nome do motorista')),
                ('mark_supply', models.CharField(max_length=50, verbose_name='Marca')),
                ('date_supply', models.DateField(verbose_name='Data de abastecimento')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Abastecimento',
                'verbose_name_plural': 'Abastecimentos',
                'ordering': ['-date_supply'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(verbose_name='Data de saída')),
                ('service', models.CharField(max_length=200, verbose_name='Serviço')),
                ('delivery_date', models.DateField(verbose_name='Data de entrega')),
                ('mark_main', models.CharField(max_length=50, verbose_name='Marca')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor')),
                ('next_service', models.DateField(verbose_name='Próximo serviço')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provider', verbose_name='Fornecedor')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
                'ordering': ['-departure_date'],
            },
        ),
    ]
